<?php
/**
 * Created by PhpStorm.
 * User: bghanem
 * Date: 13/02/2019
 * Time: 12:21
 */

namespace Bg\HelloBundle\DependencyInjection;



use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class BgHelloExtension extends Extension
{

    /**
     * Loads a specific configuration.
     *
     * @throws \InvalidArgumentException When provided tag is not defined in this extension
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        //var_dump($configs);die;
        $loader = new XmlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('services.xml');

        //$configuration = $this->getConfiguration($configs, $container);
        //$config = $this->processConfiguration($configuration, $configs);

        //var_dump($config);die;

        //$definition = $container->getDefinition('bg_hello.bg_sayhello');
        //$definition->setArgument(1, $config['min_sunshine']);
    }

    public function getAlias()
    {
        return 'bg_hello'; // TODO: Change the autogenerated stub
    }

}